module "firehose" {
  source                             = "git::https://github.com/kiro-krafters/kk-terraform-modules-wrapper.git//ch-terraform-aws-firehose?ref=main"
  prefix_company                     = "ch"
  prefix_region                      = "use1"
  application                        = "connect"
  env                                = "dev"
  destination                        = "s3"
  input_source                       = "kinesis"
  s3_bucket_arn                      = "arn:aws:s3:::s3-internal-connect-storage"
  s3_prefix                          = "example/"
  kinesis_source_stream_arn          = "arn:aws:kinesis:us-east-1:123456789012:stream/my-stream"
  enable_s3_backup                   = true
  s3_backup_bucket_arn               = "arn:aws:s3:::my-backup-bucket"
  sse_kms_key_type                   = "CUSTOMER_MANAGED_CMK"
  s3_backup_prefix                   = "backup/"
  s3_backup_error_output_prefix      = "error/"
  s3_backup_buffering_interval       = 100
  s3_backup_buffering_size           = 100
  s3_backup_compression              = "GZIP"
  s3_backup_use_existing_role        = false
  s3_backup_role_arn                 = "arn:aws:iam::AWS_ACCOUNT_ID:role/ROLE_NAME"
  s3_backup_enable_encryption        = true
  s3_backup_kms_key_arn              = "arn:aws:iam::AWS_ACCOUNT_ID:role/ROLE_NAME"
  s3_backup_enable_log               = true
  create_application_role            = false
  create_application_role_policy     = false
  application_role_service_principal = "arn:aws:iam::AWS_ACCOUNT_ID:role/ROLE_NAME"
  enable_sse                         = true
  sse_kms_key_arn                    = "arn:aws:kms:us-west-2:123456789012:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  tags                               = local.tags
}
