module "lambda_function" {
  source                                       = "git@github.com:CA-Bridge/ccaas-terraform-modules.git//terraform-aws-lambda?ref=v1.0.0"
  count                                        = var.resource_type == "FUNCTION" ? 1 : 0
  function_name                                = var.name
  create                                       = true
  description                                  = var.description
  handler                                      = var.handler
  runtime                                      = var.runtime
  environment_variables                        = var.environment_variables
  ephemeral_storage_size                       = var.ephemeral_storage_size
  event_source_mapping                         = var.event_source_mapping
  allowed_triggers                             = var.allowed_triggers
  architectures                                = var.architectures
  artifacts_dir                                = var.artifacts_dir
  authorization_type                           = var.auth_type
  assume_role_policy_statements                = var.assume_role_policy_statements
  code_signing_config_arn                      = var.code_signing_config_arn
  compatible_architectures                     = var.compatible_architectures
  compatible_runtimes                          = var.compatible_runtimes
  cors                                         = var.cors
  dead_letter_target_arn                       = var.dead_letter_target_arn
  destination_on_failure                       = var.destination_on_failure
  destination_on_success                       = var.destination_on_success
  file_system_arn                              = var.file_system_arn
  file_system_local_mount_path                 = var.file_system_local_mount_path
  image_uri                                    = var.image_uri
  invoke_mode                                  = var.invoke_mode
  hash_extra                                   = var.hash_extra
  ipv6_allowed_for_dual_stack                  = var.ipv6_allowed_for_dual_stack
  ignore_source_code_hash                      = var.ignore_source_code_hash
  kms_key_arn                                  = var.kms_key_arn
  lambda_at_edge                               = var.lambda_at_edge
  lambda_at_edge_logs_all_regions              = var.lambda_at_edge_logs_all_regions
  layer_name                                   = var.layer_name
  layer_skip_destroy                           = var.layer_skip_destroy
  layers                                       = var.layers
  license_info                                 = var.license_info
  local_existing_package                       = var.local_existing_package
  maximum_event_age_in_seconds                 = var.maximum_event_age_in_seconds
  maximum_retry_attempts                       = var.maximum_retry_attempts
  memory_size                                  = var.memory_size
  provisioned_concurrent_executions            = var.provisioned_concurrent_executions
  package_type                                 = var.package_type
  publish                                      = var.publish
  recreate_missing_package                     = var.recreate_missing_package
  recursive_loop                               = var.recursive_loop
  replace_security_groups_on_destroy           = var.replace_security_groups_on_destroy
  replacement_security_group_ids               = var.replacement_security_group_ids
  reserved_concurrent_executions               = var.reserved_concurrent_executions
  skip_destroy                                 = var.skip_destroy
  snap_start                                   = var.snap_start
  source_path                                  = var.source_path
  timeout                                      = var.timeout
  timeouts                                     = var.timeouts
  tracing_mode                                 = var.tracing_mode
  trigger_on_package_timestamp                 = var.trigger_on_package_timestamp
  trusted_entities                             = var.trusted_entities
  vpc_security_group_ids                       = var.vpc_security_group_ids
  vpc_subnet_ids                               = var.vpc_subnet_ids
  attach_async_event_policy                    = lookup(var.attach, "async_event_policy", false)
  attach_cloudwatch_logs_policy                = lookup(var.attach, "cw_logs_policy", true)
  attach_create_log_group_permission           = lookup(var.attach, "create_log_group_permission", true)
  attach_dead_letter_policy                    = lookup(var.attach, "dead_letter_policy", false)
  attach_network_policy                        = lookup(var.attach, "network_policy", false)
  attach_policies                              = lookup(var.attach, "policies", false)
  attach_policy                                = lookup(var.attach, "policy", false)
  attach_policy_json                           = lookup(var.attach, "policy_json", false)
  attach_policy_jsons                          = lookup(var.attach, "policy_jsons", false)
  attach_policy_statements                     = lookup(var.attach, "policy_statements", false)
  attach_tracing_policy                        = lookup(var.attach, "tracing_policy", false)
  cloudwatch_logs_kms_key_id                   = lookup(var.logging_configuration, "kms_key_id", null)
  cloudwatch_logs_log_group_class              = lookup(var.logging_configuration, "log_group_class", null)
  cloudwatch_logs_retention_in_days            = lookup(var.logging_configuration, "retention_in_days", null)
  cloudwatch_logs_skip_destroy                 = lookup(var.logging_configuration, "skip_destroy", false)
  logging_application_log_level                = lookup(var.logging_configuration, "log_level", "INFO")
  logging_log_format                           = lookup(var.logging_configuration, "log_format", "Text")
  logging_log_group                            = lookup(var.logging_configuration, "log_group", null)
  logging_system_log_level                     = lookup(var.logging_configuration, "sys_log_level", "INFO")
  use_existing_cloudwatch_log_group            = lookup(var.logging_configuration, "use_existing_cloudwatch_log_group", false)
  create_async_event_config                    = lookup(var.create, "async_event_config", false)
  create_current_version_allowed_triggers      = lookup(var.create, "cv_allowed_triggers", true)
  create_current_version_async_event_config    = lookup(var.create, "cv_async_event_config", true)
  create_function                              = lookup(var.create, "function", true)
  create_lambda_function_url                   = lookup(var.create, "function_url", false)
  create_layer                                 = lookup(var.create, "layer", false)
  create_package                               = lookup(var.create, "package", false)
  create_role                                  = lookup(var.create, "role", true)
  create_sam_metadata                          = lookup(var.create, "sam_metadata", false)
  create_unqualified_alias_allowed_triggers    = lookup(var.create, "unq_alias_allowed_triggers", true)
  create_unqualified_alias_async_event_config  = lookup(var.create, "unq_alias_async_event_config", true)
  create_unqualified_alias_lambda_function_url = lookup(var.create, "unq_alias_lambda_function_url", true)
  build_in_docker                              = lookup(var.docker_configuration, "build", false)
  docker_additional_options                    = lookup(var.docker_configuration, "options", [])
  docker_build_root                            = lookup(var.docker_configuration, "root_dir", "")
  docker_entrypoint                            = lookup(var.docker_configuration, "entrypoint", null)
  docker_file                                  = lookup(var.docker_configuration, "file", "")
  docker_image                                 = lookup(var.docker_configuration, "image", "")
  docker_pip_cache                             = lookup(var.docker_configuration, "pip_cache", null)
  docker_with_ssh_agent                        = lookup(var.docker_configuration, "ssh_auth", false)
  image_config_command                         = lookup(var.docker_configuration, "image_config_command", [])
  image_config_entry_point                     = lookup(var.docker_configuration, "image_config_entry_point", [])
  image_config_working_directory               = lookup(var.docker_configuration, "image_config_working_dir", null)
  number_of_policies                           = lookup(var.iam_configuration, "number_of_policies", 0)
  number_of_policy_jsons                       = lookup(var.iam_configuration, "number_of_policy_jsons", 0)
  policies                                     = lookup(var.iam_configuration, "policies", [])
  policy                                       = lookup(var.iam_configuration, "policy", null)
  policy_json                                  = lookup(var.iam_configuration, "policy_json", null)
  policy_jsons                                 = lookup(var.iam_configuration, "policy_jsons", [])
  policy_name                                  = lookup(var.iam_configuration, "policy_name", null)
  policy_path                                  = lookup(var.iam_configuration, "policy_path", null)
  policy_statements                            = lookup(var.iam_configuration, "policy_statements", {})
  lambda_role                                  = lookup(var.iam_configuration, "lambda_role", "")
  role_description                             = lookup(var.iam_configuration, "role_description", null)
  role_force_detach_policies                   = lookup(var.iam_configuration, "role_force_detach_policies", true)
  role_maximum_session_duration                = lookup(var.iam_configuration, "role_maximum_session_duration", 3600)
  role_name                                    = lookup(var.iam_configuration, "role_name", null)
  role_path                                    = lookup(var.iam_configuration, "role_path", null)
  role_permissions_boundary                    = lookup(var.iam_configuration, "role_permissions_boundary", null)
  s3_acl                                       = lookup(var.s3_configuration, "acl", "private")
  s3_bucket                                    = lookup(var.s3_configuration, "bucket", null)
  s3_existing_package                          = lookup(var.s3_configuration, "existing_package", null)
  s3_kms_key_id                                = lookup(var.s3_configuration, "kms_key_id", null)
  s3_object_storage_class                      = lookup(var.s3_configuration, "storage_class", "ONEZONE_IA")
  s3_prefix                                    = lookup(var.s3_configuration, "prefix", null)
  s3_server_side_encryption                    = lookup(var.s3_configuration, "server_side_encryption", null)
  store_on_s3                                  = lookup(var.s3_configuration, "store", false)
  s3_object_override_default_tags              = lookup(var.s3_configuration, "s3_override_defaut_tags", false)
  s3_object_tags_only                          = lookup(var.s3_configuration, "tags_only", false)
  cloudwatch_logs_tags                         = lookup(var.additional_tags, "cloudwatch_log", {})
  function_tags                                = lookup(var.additional_tags, "function", {})
  role_tags                                    = lookup(var.additional_tags, "role", {})
  s3_object_tags                               = lookup(var.additional_tags, "s3_object", {})
  tags                                         = merge(var.tags, { "map-migrated" = "123456" })
}
