module "eventbridge" {
  source                         = "git::https://github.com/kiro-krafters/kk-terraform-modules.git//terraform-aws-eventbridge?ref=main"
  bus_name                       = var.bus_name
  create_bus                     = var.bus_name == "default" ? false : var.create_bus
  rules                          = var.rules
  targets                        = var.targets
  policies                       = var.policies
  api_destinations               = var.api_destinations
  policy_json                    = var.policy_json
  policy_jsons                   = var.policy_jsons
  number_of_policies             = var.number_of_policies
  number_of_policy_jsons         = var.number_of_policy_jsons
  policy                         = var.policy
  policy_path                    = var.policy_path
  policy_statements              = var.policy_statements
  archives                       = var.archives
  bus_description                = var.bus_description
  ecs_pass_role_resources        = var.ecs_pass_role_resources
  event_source_name              = var.event_source_name
  kms_key_identifier             = var.kms_key_identifier
  schemas_discoverer_description = var.schemas_discoverer_description
  sns_kms_arns                   = var.sns_kms_arns
  trusted_entities               = var.trusted_entities
  connections                    = var.connections
  permissions                    = var.permissions
  pipes                          = var.pipes
  schedules                      = var.schedules
  schedule_groups                = var.schedule_groups
  schedule_group_timeouts        = var.schedule_group_timeouts
  create                         = true
  create_api_destinations        = lookup(var.create, "api_destinations", false)
  create_archives                = lookup(var.create, "archives", false)
  create_connections             = lookup(var.create, "connections", false)
  create_permissions             = lookup(var.create, "permissions", true)
  create_pipes                   = lookup(var.create, "pipes", true)
  create_role                    = lookup(var.create, "role", false)
  create_schedule_groups         = lookup(var.create, "schedule_groups", true)
  create_schedules               = lookup(var.create, "schedules", true)
  create_schemas_discoverer      = lookup(var.create, "schemas_discoverer", false)
  create_rules                   = lookup(var.create, "rules", true)
  create_targets                 = lookup(var.create, "targets", true)
  attach_api_destination_policy  = lookup(var.attach, "api_destination_policy", false)
  attach_cloudwatch_policy       = lookup(var.attach, "cloudwatch_policy", false)
  attach_ecs_policy              = lookup(var.attach, "ecs_policy", false)
  attach_kinesis_firehose_policy = lookup(var.attach, "kinesis_firehose_policy", false)
  attach_kinesis_policy          = lookup(var.attach, "kinesis_policy", false)
  attach_lambda_policy           = lookup(var.attach, "lambda_policy", false)
  attach_policies                = lookup(var.attach, "policies", false)
  attach_policy                  = lookup(var.attach, "policy", false)
  attach_policy_json             = lookup(var.attach, "policy_json", false)
  attach_policy_jsons            = lookup(var.attach, "policy_jsons", false)
  attach_policy_statements       = lookup(var.attach, "policy_statements", false)
  attach_sfn_policy              = lookup(var.attach, "sfn_policy", false)
  attach_sns_policy              = lookup(var.attach, "sns_policy", false)
  attach_sqs_policy              = lookup(var.attach, "sqs_policy", false)
  attach_tracing_policy          = lookup(var.attach, "tracing_policy", false)
  cloudwatch_target_arns         = lookup(var.target_arns_configuration, "cloudwatch", [])
  ecs_target_arns                = lookup(var.target_arns_configuration, "ecs", [])
  kinesis_firehose_target_arns   = lookup(var.target_arns_configuration, "kinesis_firehose", [])
  kinesis_target_arns            = lookup(var.target_arns_configuration, "kinesis", [])
  lambda_target_arns             = lookup(var.target_arns_configuration, "lambda", [])
  sfn_target_arns                = lookup(var.target_arns_configuration, "sfn", [])
  sns_target_arns                = lookup(var.target_arns_configuration, "sns", [])
  sqs_target_arns                = lookup(var.target_arns_configuration, "sqs", [])
  append_connection_postfix      = lookup(var.append_postfix_configuration, "connection", true)
  append_destination_postfix     = lookup(var.append_postfix_configuration, "destination", true)
  append_pipe_postfix            = lookup(var.append_postfix_configuration, "pipe", true)
  append_rule_postfix            = lookup(var.append_postfix_configuration, "rule", true)
  append_schedule_group_postfix  = lookup(var.append_postfix_configuration, "schedule_group", true)
  append_schedule_postfix        = lookup(var.append_postfix_configuration, "schedule", true)
  role_name                      = lookup(var.role_configuration, "name", null)
  role_description               = lookup(var.role_configuration, "description", null)
  role_force_detach_policies     = lookup(var.role_configuration, "force_detach_policies", true)
  role_path                      = lookup(var.role_configuration, "path", null)
  role_permissions_boundary      = lookup(var.role_configuration, "permissions_boundary", null)
  role_tags                      = lookup(var.role_configuration, "tags", {})
  tags                           = merge(local.tags, var.name != null && var.name != "" ? { Name = var.name } : {}, var.tags)

}
